export default {

    info: {
        name: 'Daniel Schillat',
        date: '18.06.1977',
        languages: 'Deutsch / Englisch',
        nationality: 'german',
        address: 'Naumannstr. 6',
        city: 'Berlin',
        zip: '10829',
        country: 'Germany',
        statement: 'Bridging the gap between Design and Development.',
        interests: 'UI Development, Designsystems, Atomic Design, UX Design, Frontend Consulting',
        tooling: 'React, Redux, Apollo, Sketch, Zeplin, Javascript, Foundation, Ant.Design, Material UI, React Navigation, SASS',
    },

    'roles': {
        title: 'Where i worked:',
        items: [
            {
                'from': '01.05.2017',
                'to': '',
                'role': 'Senior Frontend Developer',
                'company': 'Exozet',
                'description': '',
            },
            {
                'from': '01.01.2015',
                'to': '31.04.2017',
                'role': 'Senior Frontend Developer',
                'company': 'Zalando SE',
                'description': '',
            },
            {
                'from': '01.01.2010',
                'to': '01.01.2011',
                'role': 'Senior Developer',
                'company': 'Brand New History',
                'description': '',
            },
            {
                'from': '01.06.2003',
                'to': '31.12.2016',
                'role': 'Senior Frontend Developer',
                'company': 'Solebox',
                'description': '',
            },
            {
                'from': '01.09.2010',
                'to': '31.12.2014',
                'role': 'Senior Frontend Developer',
                'company': 'Exozet',
                'description': '',
            },
            {
                'from': '01.01.2007',
                'to': '31.12.2009',
                'role': 'Developer, Founder',
                'company': 'Shopper E-Commerce Platform',
                'description': '',
            },
            {
                'from': '01.01.2001',
                'to': '31.12.2002',
                'role': 'Developer, Founder',
                'company': 'IT Wars',
                'description': '',
            },
            {
                'from': '01.12.1999',
                'to': '31.12.2001',
                'role': 'Frontend Developer',
                'company': 'R.Ø.S.A. Berlin',
                'description': '',
            },
        ],
    },
    'projects': {
        title: 'Projects:',
        items: [
            {
                title: 'Big Brother App',
                role: 'Lead Developer',
                from: '01.12.2019',
                to: '01.03.2020',
                tools: 'React Native',
                description: '',
                link: '',
            },
            {
                title: '3sat Mediathek Web',
                role: 'Senior Frontend Developer',
                from: '01.12.2018',
                to: '01.05.2019',
                tools: 'SASS, Foundation, Javascript, Atomic Design',
                description: '',
                link: 'https://www.3sat.de',
            },
            {
                title: '3sat Mediathek App',
                role: 'Lead Developer',
                from: '01.12.2018',
                to: '01.05.2019',
                tools: 'React Native, Redux, Atomic Design',
                description: '',
                link: 'https://apps.apple.com/de/app/3sat-mediathek/id687276377',
            },
            {
                title: 'ZDF Mediathek',
                role: 'Lead Frontend Developer',
                from: '01.06.2019',
                to: '',
                tools: 'React Native, Redux, Atomic Design',
                description: '',
                link: 'https://apps.apple.com/de/app/3sat-mediathek/id687276377',
            },
            {
                title: 'ZDFtivi App',
                role: 'Frontend Developer',
                from: '01.05.2017',
                to: '31.12.2017',
                tools: 'React Native, Redux',
                description: '',
                link: '',
            },
            {
                title: 'Zalon by Zalando',
                role: 'Lead Frontend Developer',
                from: '01.01.2015',
                to: '31.03.2017',
                tools: 'SASS, Javascript, Foundation, Scala, Atomic Design',
                description: 'Implementation of the frontend architecture based on "Atomic Design" principles.',
                link: 'https://www.zalon.de',
            },
            {
                title: 'Solebox Onlinestore',
                role: 'Developer, Designer, DevOp',
                from: '01.01.2003',
                to: '31.10.2016',
                tools: 'SASS, Javascript, Magento, PHP, Atomic Design, AWS',
                description: 'Responsive Onlineshop für den berliner Sneakerstore Solebox.',
                link: 'expired',
            },
            {
                title: 'Ernst und Sohn',
                role: 'Frontend Developer',
                from: '09.01.2014',
                to: '31.12.2014',
                tools: 'Javascript, SASS, HTML',
                description: 'Responsive Website für den deutschen Verlag Ernst und Sohn.',
                link: 'https://www.ernst-und-sohn.de',
            },
            {
                title: 'RBB Online',
                role: 'Frontend Developer',
                from: '02.01.2013',
                to: '31.12.2013',
                tools: 'Javascript, SASS, HTML',
                description: 'Responsive Website für den Auftritt des RBB.',
                link: 'https://www.rbb-online.de/',
            },
            {
                title: 'Deutsche Welle Smart TV App',
                role: 'Frontend Developer',
                from: '09.01.2012',
                to: '31.12.2012',
                tools: 'SASS, Javascript, HTML',
                description: 'Smart-TV App des "Deutsche Welle Rundfunk".',
                link: '',
            }, {
                title: 'TV Digital',
                role: 'Lead Developer',
                from: '01.01.2011',
                to: '08.31.2013',
                tools: 'SASS, Javascript, HTML',
                description: 'Programmierung eines digitalen Programmführers für iOS.',
                link: '',
            }, {
                title: 'Alpha Industries',
                role: 'Lead Developer',
                from: '01.01.2009',
                to: '31.04.2009',
                tools: 'Flex Builder, Actionscript 3, PHP, MySql, Illustrator, Photoshop, Apple Motion',
                description: 'Konzept, Design & Development der Website und eines custom CMS.',
                link: '',
            },
            {
                title: 'Moonbootica',
                role: 'Lead Developer',
                from: '01.03.2010',
                to: '31.04.2010',
                tools: 'CSS, HTML, Javascript, PHP, Wordpress',
                description: 'Programmierung der Website für Moonbootica',
                link: '',
            },{
                title: 'New Balance Lifestyle',
                role: 'Lead Developer',
                from: '01.01.2009',
                to: '31.04.2009',
                tools: 'Actionscript, Mysql, PHP',
                description: 'Design & Development einer Microsite für die Lifestyle Sparte von New Balance.',
                link: '',
            }, {
                title: 'Plastic Particles',
                role: 'Lead Developer',
                from: '01.02.2003',
                to: '31.04.2003',
                tools: 'Actionscript 2, PHP, MySql',
                description: 'Konzept und Development eines Jump and Run basierten Onlineshops für Designertoys.',
                link: '',
            }, {
                title: 'RECON STORE',
                role: 'Lead Developer',
                from: '01.02.2003',
                to: '31.04.2003',
                tools: 'Actionscript, Cinema 4D, PHP',
                description: 'Konzept, Design und Development eines E-Concept-Stores für das Label der New Yorker Künstler Futura 2000 und Stash.',
                link: '',
            },
        ],
    },
    'awards': {
        title: 'Awards',
        items: [
            {
                title: 'Red Dot Design Award',
                date: '2015',
                project: 'ZDFtivi App',
                description: '',
            },
            {
                title: 'Banff Television Festival',
                date: '2012',
                project: 'Wer rettet Dina Foxx',
                description: 'Interactive, Best Cross-Platform Project, Fiction Program ',
            },
            {
                title: 'New York Festivals 2012: Gold Medal',
                date: '2012',
                project: 'Wer rettet Dina Foxx',
                description: 'Online Entertainment Program',
            },
            {
                title: 'ADC Germany Silver',
                date: '2000',
                project: 'Recon Store',
                description: 'Online Gamified Conceptstore ',
            },
            {
                title: 'ADC Germany Bronze',
                date: '2000',
                project: 'Shawne Fielding Microsite',
                description: '',
            },
            {
                title: 'Cannes Cyberlions Nominee',
                date: '2000',
                project: 'Recon Store',
                description: '',
            },
        ],
    },
    'education':
        {
            title: 'Ausbildung',
            items: [
                {
                    'from': '01.01.1997',
                    'to': '31.12.1999',
                    'title': 'Multimedia Producer',
                    'company': 'S.A.E. Institute',
                    'description': '',
                } ],
        },
    clients: [
        'Alpha Industries',
        'Aperto',
        'Atomsfair Clothing',
        'Axel Springer',
        'BMG',
        'CNN',
        'Deutsche Welle',
        'Discovery Channel',
        'Frog Design',
        'Heimat',
        'Kochstrasse',
        'Leonardo',
        'LoDown Magazine',
        'New Balance',
        'RBB',
        'Recon',
        'Redbull',
        'Siemens',
        'Solebox',
        'Stahl Corp.',
        'Swatch',
        'Universal',
        'ZDF',
    ],
}




