export default {
  info: {
    name: "Daniel Schillat",
    date: "18.06.1977",
    languages: "Deutsch / Englisch",
    nationality: "german",
    address: "Naumannstr. 6",
    city: "Berlin",
    zip: "10829",
    country: "Germany",
    intro:
      "I am specializing for over 20 years in the development of user facing applications.",
    tooling:
      "The tools i heavily use include: React, React Native, Apollo, NextJS, Typescript, Sketch, Zeplin, Figma, Material UI, Tailwind",
    phone: "+49 160 947 499 26",
    email: "ds@campsafari.de",
  },

  roles: {
    title: "Experience:",
    items: [
      {
        from: "01.07.2023",
        to: "",
        role: "Senior Frontend Developer",
        company: "The Quality Group",
        description:
          "Migrating multiple online shops built on different tech stacks to a single code base based on Remix / Shopify Hydrogen.",
      },
      {
        from: "01.08.2021",
        to: "31.05.2023",
        role: "Senior Development Consultant",
        company: "Endava",
        description:
          "I was hired to guide and lead a team for a german video streaming platform. The platform consists of multiple REST apis, a graphql backend and the frontend was built with NextJs and Apollo. My responsibilities were backend & frontend coding, UX and development consulting, creating user flows in figma, project management, writing user stories for new features, validating feature requests made by the client and mentoring other developers in the team.",
      },
      {
        from: "01.04.2020",
        to: "31.06.2021",
        role: "Lead Developer",
        company: "AXA",
        description:
          "AXA hired me to design and develop an internal process management application. This was build using NextJs, Apollo and Material UI.",
      },
      {
        from: "01.05.2017",
        to: "31.03.2020",
        role: "Senior Frontend Developer",
        company: "Exozet",
        description:
          "In this role i was mostly leading frontend development teams and helping the developers with the transition to modern tech stacks like React, Apollo and Redux as well as laying the foundations of that particular projects.",
      },
      {
        from: "01.01.2015",
        to: "31.04.2017",
        role: "Senior Frontend Developer",
        company: "Zalando SE",
        description:
          "I was hired as a lead developer to kick start Zalando´s curating shopping platform.",
      },
      {
        from: "01.01.2010",
        to: "01.01.2011",
        role: "Senior Developer",
        company: "Brand New History",
        description: "",
      },
      {
        from: "01.06.2003",
        to: "31.12.2016",
        role: "Senior Frontend Developer",
        company: "Solebox",
        description: "",
      },
      {
        from: "01.09.2010",
        to: "31.12.2014",
        role: "Senior Frontend Developer",
        company: "Exozet",
        description: "",
      },
      {
        from: "01.01.2007",
        to: "31.12.2009",
        role: "Developer, Founder",
        company: "Shopper E-Commerce Platform",
        description: "",
      },
      {
        from: "01.01.2001",
        to: "31.12.2002",
        role: "Developer, Founder",
        company: "IT Wars",
        description: "",
      },
      {
        from: "01.12.1999",
        to: "31.12.2001",
        role: "Frontend Developer",
        company: "R.Ø.S.A. Berlin",
        description: "",
      },
    ],
  },
  projects: {
    title: "Selected Projects:",
    items: [
      {
        title: "The Masked Singer App",
        role: "Lead Developer",
        from: "01.02.2020",
        to: "31.03.2020",
        tools: "React Native, Apollo Client, GraphQl",
        description:
          'Development of the mobile app for the TV show "The Masked Singer" with React-Native and Apollo Client',
        link: "",
      },
      {
        title: "Big Brother App",
        role: "Lead Developer",
        from: "01.12.2019",
        to: "01.03.2020",
        tools: "React Native, Apollo Client, GraphQl",
        description:
          'Development of the mobile app for the TV show "Big Brother" with React-Native and Apollo Client',
        link: "",
      },
      {
        title: "3sat Mediathek Web",
        role: "Senior Frontend Developer",
        from: "01.12.2018",
        to: "01.05.2019",
        tools: "SASS, Foundation, Javascript, Atomic Design",
        description:
          "Development of the foundation for frontend components and bridging the gap between design and development. This was done by establishing a common lingo for modules and components, setting up the workflow between design and development via sketch and zeplin as well as defining component APIs for engineering.",
        link: "https://www.3sat.de",
      },
      {
        title: "3sat Mediathek App",
        role: "Lead Developer",
        from: "01.12.2018",
        to: "01.05.2019",
        tools: "React Native, Redux, RxJS, Atomic Design",
        description: "",
        link: "https://apps.apple.com/de/app/3sat-mediathek/id687276377",
      },
      {
        title: "ZDF Mediathek",
        role: "Lead Frontend Developer",
        from: "01.06.2019",
        to: "",
        tools: "Foundation, Javascript, SASS, Redux, React",
        description:
          "Establishing a solid component foundation and a partly migration of the existing stack based on twig and spring boot to react and redux. The migration was done gradually via react portals.",
        link: "https://apps.apple.com/de/app/3sat-mediathek/id687276377",
      },
      {
        title: "ZDFtivi App",
        role: "Frontend Developer",
        from: "01.05.2017",
        to: "31.12.2017",
        tools: "React Native, Redux, RxJS",
        description: "",
        link: "",
      },
      {
        title: "Zalon by Zalando",
        role: "Lead Frontend Developer",
        from: "01.01.2015",
        to: "31.03.2017",
        tools: "SASS, Javascript, Foundation, Scala, Atomic Design",
        description:
          'Implementation of the client facing frontend architecture based on "Atomic Design" principles. Further development of an admin interface in React for managing orders and assembling outfits for clients.',
        link: "https://www.zalon.de",
      },
      {
        title: "Solebox Onlinestore",
        role: "Developer, Designer, DevOp",
        from: "01.01.2003",
        to: "31.10.2016",
        tools: "SASS, Javascript, Magento, PHP, Atomic Design, AWS",
        description:
          "Responsive Onlineshop for the berlin based sneaker Boutique Solebox.",
        link: "expired",
      },
      {
        title: "Ernst und Sohn",
        role: "Frontend Developer",
        from: "09.01.2014",
        to: "31.12.2014",
        tools: "Javascript, SASS, HTML",
        description:
          'Responsive Website for the german publisher "Ernst und Sohn".',
        link: "https://www.ernst-und-sohn.de",
      },
      {
        title: "RBB Online",
        role: "Frontend Developer",
        from: "02.01.2013",
        to: "31.12.2013",
        tools: "Javascript, SASS, HTML",
        description: "Responsive Website for the german TV Channel RBB.",
        link: "https://www.rbb-online.de/",
      },
      {
        title: "Deutsche Welle Smart TV App",
        role: "Frontend Developer",
        from: "09.01.2012",
        to: "31.12.2012",
        tools: "SASS, Javascript, HTML",
        description: 'Smart-TV App for "Deutsche Welle Rundfunk".',
        link: "",
      },
      {
        title: "TV Digital",
        role: "Lead Developer",
        from: "01.01.2011",
        to: "08.31.2013",
        tools: "SASS, Javascript, HTML",
        description: "Concept and Development of an EPG.",
        link: "",
      },
      {
        title: "Alpha Industries",
        role: "Lead Developer",
        from: "01.01.2009",
        to: "31.04.2009",
        tools:
          "Flex Builder, Actionscript 3, PHP, MySql, Illustrator, Photoshop, Apple Motion",
        description: "Concept, Design & Development of the Website and CMS.",
        link: "",
      },
      {
        title: "Moonbootica",
        role: "Lead Developer",
        from: "01.03.2010",
        to: "31.04.2010",
        tools: "CSS, HTML, Javascript, PHP, Wordpress",
        description: "Development of a custom Wordpress Theme",
        link: "",
      },
      {
        title: "New Balance Lifestyle",
        role: "Lead Developer",
        from: "01.01.2009",
        to: "31.04.2009",
        tools: "Actionscript, Mysql, PHP",
        description:
          "Design & Development of a microsite for New Balance Lifestyle.",
        link: "",
      },
      {
        title: "Plastic Particles",
        role: "Lead Developer",
        from: "01.02.2003",
        to: "31.04.2003",
        tools: "Actionscript 2, PHP, MySql",
        description: "Concept & Development of a Jump'n Run based Onlineshop",
        link: "",
      },
      {
        title: "RECON STORE",
        role: "Lead Developer",
        from: "01.02.2003",
        to: "31.04.2003",
        tools: "Actionscript, Cinema 4D, PHP",
        description:
          'Concept, Design & Development of an E-Concept-Store for the fashion label "RECON" made by the New York artists Futura 2000 and Stash.',
        link: "",
      },
    ],
  },
  awards: {
    title: "Awards",
    items: [
      {
        title: "Red Dot Design Award",
        date: "2015",
        project: "ZDFtivi App",
        description: "",
      },
      {
        title: "Banff Television Festival",
        date: "2012",
        project: "Wer rettet Dina Foxx",
        description:
          "Interactive, Best Cross-Platform Project, Fiction Program ",
      },
      {
        title: "New York Festivals 2012: Gold Medal",
        date: "2012",
        project: "Wer rettet Dina Foxx",
        description: "Online Entertainment Program",
      },
      {
        title: "ADC Germany Silver",
        date: "2000",
        project: "Recon Store",
        description: "Online Gamified Conceptstore ",
      },
      {
        title: "ADC Germany Bronze",
        date: "2000",
        project: "Shawne Fielding Microsite",
        description: "",
      },
      {
        title: "Cannes Cyberlions Nominee",
        date: "2000",
        project: "Recon Store",
        description: "",
      },
    ],
  },
  education: {
    title: "Ausbildung",
    items: [
      {
        from: "01.01.1997",
        to: "31.12.1999",
        title: "Multimedia Producer",
        subtitle: "S.A.E. Institute",
      },
    ],
  },
  clients: [
    "Alpha Industries",
    "Aperto",
    "Atomsfair Clothing",
    "Axel Springer",
    "BMG",
    "CNN",
    "Deutsche Welle",
    "Discovery Channel",
    "Frog Design",
    "Heimat",
    "Kochstrasse",
    "Leonardo",
    "LoDown Magazine",
    "New Balance",
    "RBB",
    "Recon",
    "Redbull",
    "Siemens",
    "Solebox",
    "Stahl Corp.",
    "Swatch",
    "Universal",
    "ZDF",
  ],
};
